### ISSUE TITLE
Migration from failure

### ISSUE THREAD

**Issue by l4l** [suharev7/clickhouse-rs#100]
[failure is deprecated](https://github.com/rust-lang-nursery/failure/pull/347) so I would suggest to replace it with either [thiserror](https://crates.io/crates/thiserror) or [snafu](https://crates.io/crates/snafu), both of them are compatible with std::error::Error. I may help you with a migration itself, but need to decide which one to choose. Personally I like the first one since it smaller and simpler to use, but the former allows more explicit error handling.

**Comment by suharev7** [comment]
Thanks for your suggestion. I've migrated into `thiserror` in v0.1.21 and v0.2.0-alpha.5.
