### ISSUE TITLE
the trait `std::future::Future` is not implemented for `clickhouse_rs::pool::futures::get_handle::GetHandle`

### ISSUE THREAD

**Issue by tx991020** [suharev7/clickhouse-rs#104]
`use std::error::Error;
use futures_util::StreamExt;
use std::str::FromStr;
use clickhouse_rs::{row, types::Block, Pool};
use async_std::task;

async fn execute(database_url: String) -> Result<(), Box<dyn Error>> {

    let ddl = r"
        CREATE TABLE IF NOT EXISTS payment (
            customer_id  UInt32,
            amount       UInt32,
            account_name Nullable(FixedString(3))
        ) Engine=Memory";

    let mut block = Block::with_capacity(5);
    block.push(row! { customer_id: 1_u32, amount:  2_u32, account_name: Some("foo") })?;
    block.push(row! { customer_id: 3_u32, amount:  4_u32, account_name: None::<&str> })?;
    block.push(row! { customer_id: 5_u32, amount:  6_u32, account_name: None::<&str> })?;
    block.push(row! { customer_id: 7_u32, amount:  8_u32, account_name: None::<&str> })?;
    block.push(row! { customer_id: 9_u32, amount: 10_u32, account_name: Some("bar") })?;
    // let pool = Pool::new(database_url());
    let pool = Pool::new("tcp://default:123456@127.0.0.1:9000/darwin?ping_timeout=42ms".to_owned());

    let mut client = pool.get_handle().await?;
    client.execute(ddl).await?;
    client.insert("payment", block).await?;
    let mut stream = client.query("SELECT * FROM payment").stream();

    while let Some(row) = stream.next().await {
        let row = row?;
        let id: u32 = row.get("customer_id")?;
        let amount: u32 = row.get("amount")?;
        let name: Option<&str> = row.get("account_name")?;
        println!("Found payment {}: {} {:?}", id, amount, name);
    }

    Ok(())
}

fn main()  {
    task::block_on(execute("tcp://default:123456@127.0.0.1:9000/darwin?ping_timeout=42ms".to_owned())).unwrap();
}

[dependencies]
clickhouse-rs = "0.1.21"
futures = "0.3.4"
futures-util = "0.3.5"
async-std = "1.6.2"

`

error[E0277]: the trait bound `clickhouse_rs::pool::futures::get_handle::GetHandle: std::future::Future` is not satisfied
  --> src/main.rs:28:22
   |
28 |     let mut client = pool.get_handle().await?;
   |                      ^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::future::Future` is not implemented for `clickhouse_rs::pool::futures::get_handle::GetHandle`

**Comment by suharev7** [comment]
try to use these dependencies:

```toml
[dependencies]
clickhouse-rs = { version = "0.2.0-alpha.5", features = ["async_std"], default-features = false }
futures = "0.3.4"
futures-util = "0.3.5"
async-std = "1.6.2"
```

and signature of `execute` function should be

```rust
async fn execute(database_url: String) -> Result<(), Box<dyn Error>> {
```

**Comment by tx991020** [comment]
thank you !
