### ISSUE TITLE
version get

### ISSUE THREAD

**Issue by somewheve** [suharev7/clickhouse-rs#106]
Hey brother, 
Your project in crate.io  version  clickhouse-rs 0.2.0-alpha.5 can't compile , I have fix it in the last pr, 
I try to use `clickhouse-rs={git="https://github.com/suharev7/clickhouse-rs/"}`, but I can't get the async-await branch . 

could you fix it?

**Comment by suharev7** [comment]
Hi,
Currently, I'm going to release a new non-beta version with your fix, but I don't think it takes less than one or two weeks. So, as a temporary solution right now, you can use:
```toml
clickhouse-rs = { git="https://github.com/suharev7/clickhouse-rs/", branch="async-await" }
```
And thanks again for your contribution.

**Comment by somewheve** [comment]
ok got it

**Comment by somewheve** [comment]
I am trying to insert a  struct in [here](https://github.com/yutiansut/QIFI).  but its too complex, I had to divide it into multiple tables.   
and also I had to build a  query function for query QIFI struct by account_cookie, user_id, and trading_day.  did you have any suggestions for how to design tables ？  
I am new to clickhouse.   Hope for your reply
