### ISSUE TITLE
Compiling under windows

### ISSUE THREAD

**Issue by bwalshe** [suharev7/clickhouse-rs#12]
This is a cool project, but it doesn't seem to build under windows at the moment. In order to get it running on my system, I had to change [this line](https://github.com/suharev7/clickhouse-rs/blob/9df5231f24133102e5ab0675e16e5423a8388fa3/clickhouse-rs-cityhash-sys/src/cc/config.h#L8) to

```
#if _WIN32 || _WIN64
```

**Comment by suharev7** [comment]
Thanks for advice
Here is commit with the fix: cfdcbf38deb072801e46d539e79a57e7729e9059

**Comment by bwalshe** [comment]
Great, it works for me. Thanks.
