### ISSUE TITLE
New release with tokio 1.0

### ISSUE THREAD

**Issue by tekjar** [suharev7/clickhouse-rs#123]
Hi. Any plans to release a new crate with tokio 1.0 support?

**Comment by suharev7** [comment]
Hi. I'm going to release a new version with tokio 1.0 (and 0.3) support.

**Comment by tekjar** [comment]
Thanks! Do you mean you want to support both Tokio 1.0 and 0.3 with feature flags? Isn't that a wasted effort given the whole ecosystem is moving to 1.0 rapidly?

**Comment by suharev7** [comment]
I was mistaken. I meant that going to support 0.1 and 1.0 branches.

**Comment by tekjar** [comment]
Cool. Thanks! Looking forward

**Comment by doowonee** [comment]
You are amazing I can't wait for  next version of  `clickhouse-rs`! By the way rusoto uses tokio 1.0 now. So I'm using previous version of rusoto because of the dependency with `clickhouse-rs`

**Comment by suharev7** [comment]
I'll try to release a new version at the beginning of next week.

**Comment by suharev7** [comment]
v1.0.0-alpha.1 has been released.
