### ISSUE TITLE
Block.apply for UUID values returns OutOfRange error

### ISSUE THREAD

**Issue by Redblueflame** [suharev7/clickhouse-rs#143]
I'm using clickhouse_rs 1.0.0-alpha1 for its async/await support, and I'm experiencing issues with importing elements to a block.
I've tried both converting the element to `Vec<(String, Value)`, and using the `row!` macro, but none did work.
Here is the concerned code:
```rust
        let val: Vec<(String, Value)> = vec![
            ("download_id".to_string(), Value::Uuid(*self.download_id.as_bytes())),
            ("time".to_string(), Value::from(self.time)),
            ("mod_id".to_string(), Value::from(self.mod_id)),
            ("version_id".to_string(), Value::from(self.version_id)),
            ("file_name".to_string(), Value::from(self.file_name)),
            ("ip".to_string(), Value::Ipv6(self.ip.octets())),
            ("user_agent".to_string(), Value::from(self.user_agent)),
            ("country_code".to_string(), Value::from(self.country_code)),
            ("latitude".to_string(), Value::from(self.latitude)),
            ("longitude".to_string(), Value::from(self.longitude)),
            ("is_proxy".to_string(), Value::from(if self.is_proxy { 1 } else { 0 })),
        ];
        block.push(val)
```
Or the other one:
```rust
block.push(row!{
            visit_id: Uuid::parse_str("936DA01F-9ABD-4d9d-80C7-02AF85C822A8").unwrap(),
            time: self.time,
            path: self.path,
            domain: self.domain,
            ip: self.ip.to_string(),
            user_agent: self.user_agent,
            country_code: self.country_code,
            latitude: self.latitude,
            longitude: self.longitude,
            session_id: self.session_id,
            consent: if self.consent { 1 } else { 0 },
            time_on_page: self.time_on_page
        })
```

For the interpretation, it seems to be a weird case, as I couldn't find the issue with a debugger, that was not able to find the root issue of it, but it seems like the <= 1 is simplified down to <1 for some reason, as the `put_param` function, was called twice, the first one properly, but not the next one (or any further).

**Comment by Redblueflame** [comment]
So it seems like I found the issue.
In my case, the `len` call for the row returns the base capacity + the element, throwing off the system. It seems to work in the tests when using 
```rust
uuid_field: Uuid::parse_str("936DA01F-9ABD-4d9d-80C7-02AF85C822A8").unwrap()
```
but doesn't when we put 
```rust
uuid_field: Value::Uuid([...])
```

But in any program that uses the row! macro with uuid seems to encounter this issue, where the empty rows are counted in the len().

So the issue seems to either be that I use directly the Value, or the Uuid in itself.

**Comment by suharev7** [comment]
I've pushed a fix. Could you check if it solves this problem?

**Comment by Redblueflame** [comment]
It works perfectly now :)
Thanks!
