### ISSUE TITLE
`GetHandle` is not a future

### ISSUE THREAD

**Issue by ArunGust** [suharev7/clickhouse-rs#150]
Is there anyway to solve this issue ?

35 |     let mut client = pool.get_handle().await?;
   |                      ^^^^^^^^^^^^^^^^^^^^^^^ `GetHandle` is not a future
   |
   = help: the trait `futures_util::Future` is not implemented for `GetHandle`
   = note: required by `futures_util::Future::poll`

**Comment by suharev7** [comment]
Which versions of `tokio-rs` and `clickhouse-rs` do you use?

**Comment by ArunGust** [comment]
thank you


[dependencies]
clickhouse-rs = "^0.1.21"
tokio = {"version"= "^1.5", features=["full"]}
futures-util = "^0.3.12"
env_logger = "0.8.3"

**Comment by ArunGust** [comment]
I changed to below and worked.  thank you

clickhouse-rs = "^1.0.0-alpha.1"
tokio = {"version"= "^1.5", features=["full"]}
futures-util = "^0.3.12"
env_logger = "0.8.3"

**Comment by ArunGust** [comment]
issue resolved
