### ISSUE TITLE
[Feature Request] Add support to specify `query_id`

### ISSUE THREAD

**Issue by lroolle** [suharev7/clickhouse-rs#176]
`query_id` is helpful in inspecting the executed query from table `system.query_log`:

> https://clickhouse.com/docs/en/operations/system-tables/query_log/

The [clickhouse-driver](https://clickhouse-driver.readthedocs.io/en/latest/) in python has already supported this feature:

> https://clickhouse-driver.readthedocs.io/en/latest/features.html#specifying-query-id

**Comment by viktortnk** [comment]
I checked the API and instead of using raw strings, you can try to construct query using
```rust
Query::new("SELECT * FROM payment").id("1")
```

**Comment by serega** [comment]
Does this actually work? Here is my test case

```rust
#[tokio::main]
async fn main() {
    let pool = Pool::new("tcp://localhost:9000");

    let mut client = pool.get_handle().await.unwrap();
    let query = Query::new("select now()").id("query-id-select-now");
    let res = client.query(query).fetch_all().await.unwrap();
    println!("{:?}", res);
}
```
Then
```sql
select query_id, event_time
from system.query_log where query = 'select now()'
order by event_time desc limit 1;

```
returns 
```
99045fc7-c50c-41dc-9eb8-7c25a2bd7307,2024-03-01 11:48:42
```


The same query using Python's clickhouse-driver

```python
from clickhouse_driver import Client
client = Client.from_url('clickhouse://localhost:9000')
res = client.execute("select now()", query_id="query-id-select-now")
print(res)
```

Then
```sql
select query_id, event_time
from system.query_log where query = 'select now()'
order by event_time desc limit 1;

```
returns the specified query id as expected
```
query-id-select-now,2024-03-01 11:57:35

```

**Comment by serega** [comment]
The solution I found is `log_comment`.

```rust
let query = Query::new("select now() settings log_comment = 'query-id-select-now'");
```

Then instead of using `query_id` I use `log_comment` field

```sql
select log_comment, event_time
from system.query_log
where log_comment = 'query-id-select-now'
order by event_time desc limit 1;
```

`query-id-select-now,2024-03-01 12:53:55`
