### ISSUE TITLE
Hanging and high cpu usage

### ISSUE THREAD

**Issue by hwchen** [suharev7/clickhouse-rs#2]
First, thanks so much for writing this! I'm using this in one of my projects right now.

I'm using actix-web, and calling out to clickhouse here: https://github.com/hwchen/tesseract/blob/master/tesseract-server/src/handlers/aggregate.rs#L111

I think I'm using it correctly; but I've been able to induce a hang (with 100% of one core usage) pretty reliably by sending a two requests concurrently.

So basically, I start up the server, send 2 requests which call clickhouse simultaneously. One resolves, and the other one hangs, using 100% of one core.

Looking at `sudo perf top` I get
```
  99.05%  tesseract                [.] _ZN88_$LT$clickhouse_rs..block..block..ReadBlockFuture$u20$as$u20$futures..future..Future$GT$4poll17h48077bff47d8f67fE
```
I'm not super familiar with futures, but would be happy to look further if you can give me some guidance.

Or let me know if there's anything else I can do.

**Comment by hwchen** [comment]
Ah, I just noticed there's a v0.1.1; I was using v0.1.0. I don't know if it make a difference, but I'll try upgrading.

**Comment by suharev7** [comment]
Yes, v0.1.1 should solve this issue.

**Comment by hwchen** [comment]
thanks, looks like this did fix the issue!
