### ISSUE TITLE
streaming

### ISSUE THREAD

**Issue by hwchen** [suharev7/clickhouse-rs#22]
Hello!

I want to thank you again for writing this driver, it's been so helpful to me.

I also wanted to ask if you have any thoughts on streaming the results (i.e. by row).

Thanks again!

**Comment by suharev7** [comment]
Hello!

Since version 0.1.7 you can use `fold` method to iterate by rows:

```rust
pool
.get_handle()
.and_then(move |c| {
    c.query("SELECT * FROM system.numbers LIMIT 10")
        .fold(0_u64, |acc, row| {
            let number: u64 = row.get("number")?;
            Ok(acc + number)
        })
})
```

or `fold_blocks` to iterate by blocks.

**Comment by hwchen** [comment]
Wow, great!
