### ISSUE TITLE
Possible bug in pool

### ISSUE THREAD

**Issue by hwchen** [suharev7/clickhouse-rs#23]
Hello,

I may have found a bug in the handling of new connections which causes a race condition.

The effect is that I've been able to semi-reliably cause a panic. (Although, I do have to send thousands of concurrent requests at my app over several minutes to cause it to happen).

If this is the bug, I've also created a fix, you can see it in the pull request. I don't know if I'm understanding all the pool logic correctly, so feel free to ask for changes, or just close and fix yourself.
Pull request: #24 

I'm currently testing the fix through a long-running load test, but wanted to get the pull request in first to hear your thoughts on it. I'm not sure you have a way to reliably reproduce though.

(The fix only directly addresses the first of these errors, I'm not exactly sure if the others will also be fixed, but I think it might)

Errors:

```
thread 'arbiter:3c5ae82c-8c17-442d-9b94-4285fed8c742:actix-net-worker-7' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/ec194646fef1a467073ad74b8b68f6f202cfce97/src/libcore/slice/mod.rs:2461:14
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: std::panicking::rust_panic_with_hook
   5: <unknown>
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic_bounds_check
   9: <unknown>
  10: <clickhouse_rs::pool::futures::get_handle::GetHandle as futures::future::Future>::poll
  11: <unknown>
  12: <unknown>
  ...
```

```
thread 'arbiter:295230d8-3040-4dbf-8573-9e5c40307fc3:actix-net-worker-1' panicked at 'cannot poll MapErr twice', src/libcore/option.rs:1040:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: std::panicking::rust_panic_with_hook
   5: <unknown>
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_failed
   9: <unknown>
  10: <unknown>
  11: <clickhouse_rs::pool::futures::get_handle::GetHandle as futures::future::Future>::poll
...
```

```
thread 'arbiter:c9c90e43-7289-480f-8b2e-1a43d4e24518:actix-net-worker-5' panicked at 'cannot poll a chained future twice', /home/hwchen/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/chain.rs:33:28
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: std::panicking::rust_panic_with_hook
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <clickhouse_rs::pool::futures::get_handle::GetHandle as futures::future::Future>::poll
...
```

**Comment by hwchen** [comment]
Also was able to create this error:
```
thread 'arbiter:1cb5a1a0-4870-46d5-83e3-302d9c1dcf2d:actix-net-worker-6' panicked at 'cannot poll Fold twice', /home/hwchen/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/stream/fold.rs:54:33
 note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}} at src/libstd/sys_common/backtrace.rs:58 at src/libstd/panicking.rs:200
   3: std::panicking::default_hook at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook at src/libstd/panicking.rs:478
   5: std::panicking::begin_panic
   6: <futures::future::map::Map<A, F> as futures::future::Future>::poll
   7: <futures::future::chain::Chain<A, B, C>>::poll
   8: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
   9: clickhouse_rs::pool::Pool::poll
  10: <clickhouse_rs::pool::futures::get_handle::GetHandle as futures::future::Future>::poll
  11: <futures::future::chain::Chain<A, B, C>>::poll
  12: <futures::future::chain::Chain<A, B, C>>::poll
  13: <futures::future::from_err::FromErr<A, E> as futures::future::Future>::poll
  14: <futures::future::chain::Chain<A, B, C>>::poll
  15: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
  16: <futures::future::from_err::FromErr<A, E> as futures::future::Future>::poll
  17: <futures::future::chain::Chain<A, B, C>>::poll
  18: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
  19: <futures::future::chain::Chain<A, B, C>>::poll
  20: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
  21: <actix_web::with::WithHandlerFut<T, S, R> as futures::future::Future>::poll
  22: <actix_web::pipeline::PipelineState<S, H>>::poll
  23: <actix_web::pipeline::Pipeline<S, H> as actix_web::server::handler::HttpHandlerTask>::poll_io
  24: <actix_web::server::h1::Http1Dispatcher<T, H>>::poll_handler
  25: <actix_web::server::h1::Http1Dispatcher<T, H>>::poll
  26: <actix_web::server::channel::HttpChannel<T, H> as futures::future::Future>::poll
  27: <actix_net::service::and_then::AndThenFuture<A, B> as futures::future::Future>::poll
  28: <futures::future::chain::Chain<A, B, C>>::poll
  29: futures::task_impl::std::set
  30: <futures::task_impl::Spawn<T>>::poll_future_notify
  31: tokio_current_thread::CurrentRunner::set_spawn
  32: <tokio_current_thread::scheduler::Scheduler<U>>::tick
  33: <tokio_current_thread::Entered<'a, P>>::tick
  34: <tokio_current_thread::Entered<'a, P>>::block_on
  35: <std::thread::local::LocalKey<T>>::with
  36: <std::thread::local::LocalKey<T>>::with
  37: <std::thread::local::LocalKey<T>>::with
  38: <std::thread::local::LocalKey<T>>::with
  39: tokio::runtime::current_thread::runtime::Runtime::block_on
```

**Comment by hwchen** [comment]
Ok, I think I've been able to reproduce the error relatively reliably using my whole app.

I have a script of 60 requests which I send simultaneously to my app, then 1s after the last response is received, repeat; forever.

Of the last 10 times I ran the script, I was able to get it to error 10 times, each within about 3 minutes. So now I'll try a similar test on the patched version.

Looks like previously I was trying to go for large batch requests, but it makes sense it's easier to trigger the error every new set of requests so the total number doesn't matter (past a certain threshold).

**Comment by hwchen** [comment]
Ok, my patch has been running for several times the runtime of each of the error runs, now without error, so I'm satisfied on my end that the error is fixed by the pull request.

But let me know if you'd like me to try and construct a simpler sample that can reproduce the error.

Or, if you have ideas for how to construct a test as part of a test suite, let me know.

**Comment by suharev7** [comment]
Hello,

Thanks a lot for discovering this bug and for your patch.

It looks like that method `poll` of the instance which returned from method `fold` (here src/lib.rs:252) is called in concurrency and your patch guard it here src/pool/mod.rs:200, so I think it should solve this issue. But I won't be able to reproduce this bag, so I can't be sure.

And another one I notice you use `mysql_async` for Tesseract, and I took its implementation of a connection pool as a base for clickhouse-rs' implementation (you can find `handle_futures` there https://github.com/blackbeam/mysql_async/blob/master/src/conn/pool/mod.rs), so  I think mysql_async maybe have this issue.

**Comment by suharev7** [comment]
Here [test](https://github.com/suharev7/clickhouse-rs/commit/12fd88b30954eb387ee8b9a90689dabd204fe22c)

**Comment by hwchen** [comment]
Nice! You were able to reproduce the bug in the test?

I'll mention this to the mysql async crate.
