### ISSUE TITLE
Array support

### ISSUE THREAD

**Issue by szlend** [suharev7/clickhouse-rs#36]
Are there any plans for adding support for Arrays? I would be interested in implementing this myself (with some guidance) if not.

I tried to look if I could implement this using existing building blocks in the library, but I got stuck immediately in `types::Value`. The first idea was to make the enum recursive by adding `Array(List<Value>)` to it. However this would allow mixing different types. We could make a new Array type like `struct Array (SqlType, List<Value>)` which wouldn't allow inserting different values, though that is still pretty inefficient. I think the most efficient way would be to make 
 `Value` generic like `Value<T = ()>` and then we could add an `Array(List<T>)` to the enum.

I'm not sure what the best approach would be here. What do you think?

**Comment by suharev7** [comment]
I have not any plans for adding support for Arrays (at least in the foreseeable future), so it would be great if you could implement it and feel free to ask any question if you need. 
I think Array type like `Array(SqlType, List<Value>)` would be best to choose because it will allow getting the type of empty list.

**Comment by hwchen** [comment]
Any movement on this? This might be useful to me in the near future, and I would be willing to implement.

**Comment by szlend** [comment]
Hey, sorry but I got stuck on something pretty early on and I needed a solution fast so I just worked around it by converting the array into a comma delimited string. I might attempt it again because I know I'll need it for inserts eventually, but definitely not in the following two months.

**Comment by suharev7** [comment]
I have added a basic implementation of arrays, and it's available since v0.1.13.
You can check out an example [here](https://github.com/suharev7/clickhouse-rs/blob/master/examples/array.rs).

**Comment by hwchen** [comment]
wow, that's awesome, thanks!
