### ISSUE TITLE
Blob support

### ISSUE THREAD

**Issue by loyd** [suharev7/clickhouse-rs#39]
Hello, thanks for the crate!

According to [the clickhouse documentation](https://clickhouse.yandex/docs/en/data_types/string/), the `String` value can contain an arbitrary set of bytes, not only valid utf8. It's useful for storing messages stored in a binary format.

At the moment clickhouse-rs doesn't support it. What about `Value{Ref}::Blob`?

**Comment by suharev7** [comment]
Hello, thanks for the great issue!
I've added binary string support since 0.1.12 version. Here is an [example](https://github.com/suharev7/clickhouse-rs/blob/master/examples/binary.rs) of how to use it.

**Comment by loyd** [comment]
Thank you very much for your quick response!

I think the issue can be closed?

**Comment by suharev7** [comment]
+1
