### ISSUE TITLE
Decimal support

### ISSUE THREAD

**Issue by Riateche** [suharev7/clickhouse-rs#41]
If I try to select a decimal value from a table, I get the following error:
```
Unsupported column type "Decimal(18, 9)".
```
It would be nice if I could get the internal representation of decimal as `i32` or `i64`.

**Comment by suharev7** [comment]
`clickhouse-rs` doesn't support decimal values right now. 
I'm going to add decimals since the next version.

**Comment by suharev7** [comment]
I've added an implementation of decimal, and it's now available since `v0.1.13`.
You can see how to get the internal representation of decimal [here.](https://docs.rs/clickhouse-rs/0.1.13/clickhouse_rs/types/struct.Decimal.html#method.internal)

**Comment by g302ge** [comment]
this bug still raise in the version "clickhouse-rs = "1.0.0-alpha.1"
