### ISSUE TITLE
Tokio v0.2

### ISSUE THREAD

**Issue by athre0z** [suharev7/clickhouse-rs#46]
Hey there,

as I'm sure you already heard, Tokio has recently released the first alpha version of v0.2, finally bringing async/await without combinator madness. Do you have any plans to migrate towards it anytime soon? Do you want to wait for the final?

**Comment by athre0z** [comment]
https://async.rs/blog/announcing-async-std/

This is an alternative to Tokio v0.2 that looks like it would be worth considering, promising single-alloc tasks as well as async variants of pretty much everything in std.

**Comment by suharev7** [comment]
Hey,
I'm also looking forward to adding async/await support, but I think I'll be able to do it not early than by the end of September. And thank for suggest about asyn_std I'll think about it.

**Comment by tlightsky** [comment]
look forward for this feature too

**Comment by suharev7** [comment]
I've published alpha with Tokio v0.2 and async/await support.

**Comment by athre0z** [comment]
I had some time to check it out -- great work so far! Thank you for making this happen so quickly!

One thing I noticed is an apparent lack of APIs to obtain & convert a block's whole column at once -- I can only find the `.get(col, row)` API. When profiling a rather big select query (>2 bil rows), these getters account for > 15% of my execution time. Perhaps I'm missing a better way.

**Edit:** I'm guessing that index access makes it hard for LLVM to optimize out bounds checks?

**Comment by suharev7** [comment]
Is it suitable for your case?

```rust
let mut stream = client.query("SELECT * FROM system.numbers LIMIT 2000000;").stream_blocks();

    while let Some(block) = stream.next().await {
        let block = block?;

        for i in 0..block.row_count() {
            let value: u64 = block.get(i, 0)?;
            ...
        }
    }
```

**Comment by athre0z** [comment]
Thank you for the quick reply! This is what I'm currently doing.

The issue with the current `.get(row_idx, col_idx)` interface is that it induces a bounds check as well as the SQL type conversion code for each get call. The bound checks occur due to the integer indexing and could be optimized away if an API existed that returned a whole column as a slice, allowing users to zip them together for iteration, omitting any bound checks.

The code below compiles to the following assembly (release build):

```rust
use clickhouse_rs::{errors::Error, Pool};
use futures::StreamExt;
use tokio;

#[tokio::main]
async fn main() -> Result<(), Error> {
    let database_url = "tcp://localhost:9000";
    let pool = Pool::new(database_url);
    let mut client = pool.get_handle().await?;

    let mut stream = client
        .query("SELECT number as n1, number as n2, number as n3 FROM numbers(100000000)")
        .stream_blocks();

    let mut sum = 0;
    while let Some(block) = stream.next().await {
        let block = block?;

        for i in 0..block.row_count() {
            let v1: u64 = block.get(i, 0)?;
            let v2: u64 = block.get(i, 1)?;
            let v3: u64 = block.get(i, 2)?;
            sum = v1 + v2 + v3;
        }
    }

    dbg!(sum);

    Ok(())
}
```

![oIf2Xgvg2Ztlotqd](https://user-images.githubusercontent.com/6553158/65511493-a2130080-ded7-11e9-8b05-ea9f6d3b0a2a.jpg)
Each encircled block represents one get call, each containing a call to the `.at` function that in turn performs a bound check as well as the SQL type conversion, going through the match statement etc.

When profiling, the getter's bound-checks and type conversion code accounts for about 10% of avoidable overhead.

![2SJTPraZwRywqiQd](https://user-images.githubusercontent.com/6553158/65511654-f1f1c780-ded7-11e9-9ed0-75c6d1ee7e0d.jpg)

However, now that we have this profiler output for this reduced example at hand, it becomes obvious that we should probably instead look at `clickhouse_rs::types::column::numeric::VectorColumnData<T>::load` first -- it accounts for 67% of execution time, pretty much entirely spent in memmove and bzero. Are you in general okay with using unsafe operations for the sake of significantly boosted performance? Just reading the data into uninitialized memory would likely trivially eliminate the whole bzero section (29% performance boost).

**Comment by suharev7** [comment]
[Here](https://github.com/suharev7/clickhouse-rs/commit/854c54348ed2401fb0dc330b2ba8cf81b6d8aa2d) I got rid of some `memmove` and `bzero` sections.
And about API: because of internal representation, it's not always possible to represent the whole column as a slice, so we can add method which will return a slice when possible and error/none else. But I'm not sure if this is a good idea.

**Comment by athre0z** [comment]
Great changes, I notice a performance improvement that pretty much perfectly corresponds to my prediction of 29% -- I am now bottlenecked by IO rather then the Rust client!

Due to the whole bzero being gone, the getters now account for about 18% of execution time. Regarding returning slices in a fallible manner: well, that is unfortunate, but in this case I don't think that it would be a good idea to have such an API either.

**Edit:** I noticed that this lib profits from compiling with LTO pretty brutally -- it results in a 30%  performance boost for our example! It also removes the getters from the profiler output, but that will likely be due to aggressive inlining & the profiler sucking at tracking such functions.

**Comment by suharev7** [comment]
I decided to try to [implement it](https://github.com/suharev7/clickhouse-rs/blob/async-await/src/types/block/mod.rs#L246) to measure the consequences.

**Comment by athre0z** [comment]
Using this API instead of `.get(x, y)` legitimately cut my CPU time in half again -- that is a LOT more improvement than I expected! Looks like the getter must have confused the branch predictor / the cache in some way!

Using
```rust
for ((v1, v2), v3) in c1.iter().zip(c2).zip(c3) {
    sum = v1 + v2 + v3;
}
```
instead of the integer index access from your example shaves off another few percent of CPU time (even fewer bound checks). Also, the restriction of not working on `fetch_all` results is pretty acceptable IMO -- I was assuming that it would not work with some SQL types of something, which would have been a lot worse.

**Edit:**
Because Rust is now aware of all slice bounds before entering the loop, the inner tight loop is now reduced from the monstrosity on my previous screenshot to this tiny thing (using `.zip(...)`):
<img width="381" alt="sgGDm6HV0VewaL3B" src="https://user-images.githubusercontent.com/6553158/65788647-d4349480-e15b-11e9-822f-53554732d237.png">

**Edit 2:**
Example using integer indexing of the column slice:
<img width="1306" alt="S91fGWAkmTohtzCQ" src="https://user-images.githubusercontent.com/6553158/65788889-6b99e780-e15c-11e9-924f-4da9c0941b43.png">

**Comment by suharev7** [comment]
You correctly assumed. We can't get a slice of `String`/`FixedString`/`Nullable`/`Array` and for `Date`/`DateTime`/`Decimal` possible to get only internal representation as `&[u32]`/`&[u64]`.
I'm going to add a generic parameter to block because it allows statically to check the restriction of calling `get_column_slice` on `fetch_all` results and also implement some method which will return an iterator without limitations of slices.

**Comment by suharev7** [comment]
I've added [the method](https://github.com/suharev7/clickhouse-rs/blob/0c0cfb0490b6e5c9356669da2146b6eaa4408d7a/src/types/column/mod.rs#L171) that returns an iterator of a column. It works with all types and should have the same performance as work with slices.

**Comment by suharev7** [comment]
I added support of `async-std` since v0.2.0-alpha.3.

**Comment by athre0z** [comment]
Wow, that's great! This is probably the best support that I have ever received on an open-source project -- you rock, keep it up!
