### ISSUE TITLE
Connect to tls-only Clickhouse server

### ISSUE THREAD

**Issue by utterstep** [suharev7/clickhouse-rs#47]
Currently it's only possible to connect to Clickhouse server via TCP, but there is no option to connect via TLS.
I've bumped into this problem while trying to connect to TLS-only Clickhouse installation.

Is there any possibility to implement TLS option?

I can try it myself, if you currently have no time for that :)

In that case I'd ask if by any chance you can provide me with some advices on how you'd like it to be on the API side (I thought about yet another URI option like `secure`) and on the inner side (like, should there be two different `ClickhouseTransport`s, or is it better to abstract it behind `ClickhouseTransport.inner`? I'm thinking about latter).

Anyway, thanks for this project, hope you'll find time to look into this issue :)

**Comment by suharev7** [comment]
Right now I'm working on Tokio 0.2 support, and when I finish, there is no guarantee that I will have free time. So it would be great if you could implement TLS support.

In case you decide to do it:

About API, I think it's better to see how it has done in any existing implementation  ([Golang driver](https://github.com/kshvakov/clickhouse) for example), but anyway it's up to you.

And about the inner side, I think it's needed to do something like [Endpoint](https://github.com/blackbeam/mysql_async/blob/18417fd597e30d9e7dcacc99a99c5c01cbfa8522/src/io/mod.rs#L45) from `mysql_async`.

And feel free to ask any question if you need.

**Comment by suharev7** [comment]
Any movement on this? I'm going to implement this next week if you didn't start.

**Comment by utterstep** [comment]
Geez :(
I've implemented it, but hadn't made PR yet — still working on putting this behind feature flag :(

**Comment by suharev7** [comment]
It's a great job. Notify me when complete.

**Comment by suharev7** [comment]
Published in `v0.1.18`.

**Comment by riderx** [comment]
@suharev7 i have issue with tls on my side it seems my Clickhouse cloud instance has invalid SSL ( when i try with table plus ) so the validation fail.
Can we have option to connect in TLS and skip validation ?

**Comment by suharev7** [comment]
Yes, there is a [skip_verify](https://github.com/suharev7/clickhouse-rs/blob/757e98b6ece84ea6be96f5992cd897a3cd65a6b5/examples/simple.rs#L53) parameter.
