### ISSUE TITLE
Insert by Row?

### ISSUE THREAD

**Issue by volfco** [suharev7/clickhouse-rs#48]
Is there any chance support could be added for insertion by row?

It seems anti-pattern with the other drivers to insert data column by column and not row by row.

**Comment by suharev7** [comment]
I think it's possible to add method `push` into `Block`, so example from readme will look like:
```rust
let mut block = Block::new();
block.push(row!{ "customer_id": 1, "amount": 2, "account_name": Some("foo") })?;
block.push(row!{ "customer_id": 3, "amount": 4, "account_name": None })?;

...

client.insert("payment", block).await?;
```

**Comment by volfco** [comment]
That would be amazing.

**Comment by suharev7** [comment]
I've published this future, and it's [documentation](https://docs.rs/clickhouse-rs/0.2.0-alpha.2/clickhouse_rs/macro.row.html) for row macros.

**Comment by athre0z** [comment]
While having an additional by-row interface is great, I just want to say that I really like the column based one. It matches ClickHouse's internal data representation and the wire format and is very efficient. Please don't remove it! :)

**Comment by suharev7** [comment]
Ok, I won't do it. :)
