### ISSUE TITLE
query timeout?

### ISSUE THREAD

**Issue by jspeis** [suharev7/clickhouse-rs#49]
is there a way to set a timeout limit for a given query so that the query could be cancelled if it doesn't execute in a given time frame?

if it doesn't exist, I'd be happy to try and implement that if you can provide some pointers

**Comment by suharev7** [comment]
Right now `clikhouse_rs` doesn't support timeouts for query operations. 
I don't think that it is hard to implement it. You need to wrap the stream from [stream_blocks](https://github.com/suharev7/clickhouse-rs/blob/async-await/src/types/query_result/mod.rs#L70) into a [timeout](https://docs.rs/tokio/0.2.0-alpha.5/tokio/timer/struct.Timeout.html). Use [Options](https://github.com/suharev7/clickhouse-rs/blob/async-await/src/types/options.rs#L132) to pass parameters, and you can use [ping](https://github.com/suharev7/clickhouse-rs/blob/async-await/src/lib.rs#L288) method as an example.

**Comment by athre0z** [comment]
This can be achieved using query / session specific settings. Just use
```rust
c.execute("SET max_execution_time = 1337")
``` 
to set the timeout in seconds for your session. 

To allow this on a per-query basis, you would have to [extend this piece of code](https://github.com/suharev7/clickhouse-rs/blob/async-await/src/types/cmd.rs#L95) to allow users to actually provide custom per-query settings in some way and then send them one string at a time, finishing up with an empty string (IIRC).

**Comment by jspeis** [comment]
Going to close this! Thanks @suharev7 for accepting the PR and also thanks @athre0z for the tip as well.

**Comment by suharev7** [comment]
Thanks again for your contribution. Your test helped discovered some bug.

**Comment by jspeis** [comment]
@suharev7 thanks for getting this merged to master and for the additional fixes. Would be planning to do a v16 release soon? Would love to pull in these changes in our project and just wondering if we will use the crates version or point at a commit hash in the meantime otherwise. Thanks again!

**Comment by suharev7** [comment]
I'm going to publish it this weekend.

**Comment by suharev7** [comment]
Published as [v0.1.16](https://crates.io/crates/clickhouse-rs/0.1.16)

**Comment by jspeis** [comment]
Thanks!
