### ISSUE TITLE
Connection Pool

### ISSUE THREAD

**Issue by hwchen** [suharev7/clickhouse-rs#7]
Hello,

Are there plans to have a connection pool? Or should I use something like [bb8](https://github.com/khuey/bb8)

**Comment by suharev7** [comment]
Hello,
I'm also needed it. So I'll try to implement it.

**Comment by suharev7** [comment]
0.1.4 version with connection pool has been released.

**Comment by hwchen** [comment]
Awesome! thanks so much, testing it out now.
