### ISSUE TITLE
Insert JSONEachRow supporting.

### ISSUE THREAD

**Issue by c-solo** [suharev7/clickhouse-rs#73]
I've tried insert JSONEachRow. Like this:
```rust
 let query = format!(r#"INSERT INTO payment FORMAT JSONEachRow {"customer_id":"34","amount":6,"account_name":"bar"};"#);
client.execute(query).await.unwrap();
```
and got a timeout error.
Seems like `query` and `execute` methods are not suitable with INSERT.
Could I somehow do INSERT with JSONEachRow?

**Comment by suharev7** [comment]
`clickhouse-rs` works with Native format, not JSON*. You shouldn't use `FORMAT` keyword in any request if you work with [any native driver](https://github.com/mymarilyn/clickhouse-driver/issues/34). Right now [insert](https://docs.rs/clickhouse-rs/0.2.0-alpha.3/clickhouse_rs/struct.ClientHandle.html#method.insert) method is the only way data can be sent over Native protocol.

**Comment by c-solo** [comment]
Ok, got it. Thank you.
