### ISSUE TITLE
client hello outputs raw server credentials

### ISSUE THREAD

**Issue by jspeis** [suharev7/clickhouse-rs#75]
Would it be possible to disable [this line](https://github.com/suharev7/clickhouse-rs/blob/master/src/lib.rs#L283)? Because at the moment it seems like it may cause credentials to get logged to the output in plaintext

**Comment by dingxiangfei2009** [comment]
Just for the record: 
permalink cf. https://github.com/suharev7/clickhouse-rs/blob/69b69be02d031b31fd7a8473264fd93f67982b0b/src/lib.rs#L283

**Comment by suharev7** [comment]
May it be better to remove from the output only credentials?

**Comment by jspeis** [comment]
Yup! That could be nice. Though perhaps it should be a debug level message instead of info?

**Comment by jspeis** [comment]
Thanks for updating! Just wondering if you were planning to do an 0.1.19 release?

**Comment by suharev7** [comment]
Published in [v0.1.19](https://crates.io/crates/clickhouse-rs/0.1.19)
