### ISSUE TITLE
Return ClientHandle in case of recoverable errors

### ISSUE THREAD

**Issue by dingxiangfei2009** [suharev7/clickhouse-rs#77]
Currently the futures return only `Error` enums even in case of recoverable errors such as concurrent queries hitting the maximum allowed by the ClickHouse server. I propose that we can return the `ClientHandle` back to some `Error` variants that corresponds to recoverable errors.

**Comment by suharev7** [comment]
Published in [0.1.20](https://crates.io/crates/clickhouse-rs/0.1.20).
