### ISSUE TITLE
Reusing handle after dropped stream_blocks leads to panic

### ISSUE THREAD

**Issue by l4l** [suharev7/clickhouse-rs#83]
Now the following code compiles, but panics, once handle is reused, with a stacktrace leading to [PoolBinding::detach](https://github.com/suharev7/clickhouse-rs/blob/master/src/pool/mod.rs#L93):

```rust
let blocks = handle.query(some_query).stream_blocks();
// do smth with blocks
drop(blocks);

handle.query(other_query).stream().next().await // <- panic
```

Haven't tested other combinations of `QueryResult` functions, those might also trigger the same behavior.

**Comment by suharev7** [comment]
Fix published in [0.2.0-alpha.4](https://crates.io/crates/clickhouse-rs/0.2.0-alpha.4).
