### ISSUE TITLE
Use backticks for column names in insert block queries

### ISSUE THREAD

**Issue by karpovr** [suharev7/clickhouse-rs#84]
Using ```block.column(col_name, col_from)``` for block population and then inserting it to server results in a query with "col_name" as is (without backticks): 

```INSERT INTO db.table1 (id, ns:exampleAttr1, ns:exampleAttr2, ...) VALUES``` 

which leads to a syntax error due to colon used in column name.

Adding backticks manually to "col_name" results in a query like: 

```INSERT INTO db.table1 (`id`, `ns:exampleAttr1`, `ns:exampleAttr2`, ...) VALUES``` 

But with another error complaining that there is no column with \`id\` in a block.

Is it a bug or there is some other way to use column names with spaces and special characters (delimiters)?

```clickhouse-rs = "0.2.0-alpha.4"```

And thanks a lot for your work!

**Comment by suharev7** [comment]
Fix published in [0.1.20](https://crates.io/crates/clickhouse-rs/0.1.20).
