### ISSUE TITLE
Alternative hosts support for load-balancing

### ISSUE THREAD

**Issue by sergeyzenchenko** [suharev7/clickhouse-rs#97]
Hey, any plans to add client side load balancing? Like in [official clickhouse-go](https://github.com/ClickHouse/clickhouse-go) client? (alt_hosts option)

If not, when any recommendation on how to implements it properly using multiple connections at application level?

thanks for rust client! We've been thinking about deploying separate go service just for clickhouse before I've found it :)

**Comment by suharev7** [comment]
Implementation published in v0.1.21 and v0.2.0-alpha.5.

**Comment by sergeyzenchenko** [comment]
Thanks! @suharev7
