### ISSUE TITLE
Release 0.2.x with async/await support

### ISSUE THREAD

**Issue by hombit** [suharev7/clickhouse-rs#99]
Thank you for the great crate. Do you have any plans to release next version with async/await support?

**Comment by l4l** [comment]
Indeed, it seems that async dependencies already moved to stable, so there's no need in alpha.

But I'd rather suggest to take a look at sync and async branches parity in terms of features. Particularly, some missing commits in async-await branch:

- https://github.com/suharev7/clickhouse-rs/commit/1ff14dccc5da118de09d89f861ddd352dfeaec5b
- https://github.com/suharev7/clickhouse-rs/commit/c7a84db384610ed3bf365513427481217b0dd2a1
- https://github.com/suharev7/clickhouse-rs/commit/5a98c549489172891d4b9a034a2ec2c6fd86a0b0
- https://github.com/suharev7/clickhouse-rs/commit/a9808d9c583375b89f26ba5e461436309672b860
- https://github.com/suharev7/clickhouse-rs/commit/27f1938e3adc55852132a786eb8ee8909b82174e

Maybe it's even better merge fixes into a single branch, behind related features, so most of the features will be available nevertheless of the sync/async backend.

**Comment by suharev7** [comment]
Right now, there are a few features that were not ported into 0.2.x branch yet, but I think the next 0.2.x version will be non-alpha.

It would be better to extract a separate I/O layer to an external library, but it's too big refactoring, so I don't have enough time to make it soon.

And this issue duplicates [this one,](https://github.com/suharev7/clickhouse-rs/issues/46) so I close it.
